- hosts: terraform-ansible
  tasks:
    - name: instalando o python3 e virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
      # Para clonar uma API de exemplo dentro da máquina.
      
    - name: Git Clone
      ansible.builtin.git:
        repo: https://github.com/alura-cursos/clientes-leo-api.git
        dest: /home/ubuntu/teste/  # Removi a aspa simples no final do 'dest'
        version: master
        force: yes ## para forçar a pegar a versão mais nova do nosso código.

    - name: instalando dependências com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/teste/venv
        requirements: /caminho/do/arquivo/requerimentos.txt  # Substitua pelo caminho correto do arquivo de requerimentos
        name:
          - Django
          - djangorestframework

    - name: verificando se o projeto já existe 
      stat:
        path: /home/ubuntu/teste/setup/settings.py
      register: projeto
      
    - name: iniciando o Projeto
      shell: '. /home/ubuntu/teste/venv/bin/activate; django-admin startproject setup /home/ubuntu/teste/'
      when: not projeto.stat.exists
      
    - name: Alterando o hosts do settings
      lineinfile:
        path: /home/ubuntu/teste/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
